// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"git.code.oa.com/yifenglu/qdgo-bossapi/api/internal/dao"
	"git.code.oa.com/yifenglu/qdgo-bossapi/api/internal/server"
	"git.code.oa.com/yifenglu/qdgo-bossapi/api/internal/service"
	"git.code.oa.com/qdgo/core/net/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (*http.Server, error) {
	daoDao, err := dao.New()
	if err != nil {
		return nil, err
	}
	serviceService := service.New(daoDao)
	httpServer := server.New(serviceService)
	return httpServer, nil
}

// wire.go:

var daoProvider = wire.NewSet(dao.New)

var serviceProvider = wire.NewSet(service.New)

var serverProvider = wire.NewSet(server.New)
